### ISSUE TITLE
Require that addRow & setHeading column data is provided in the form of array

### ISSUE THREAD

**Issue by gajus** [sorensen/ascii-table#13]
The current API allows providing column values using variable number of arguments, e.g.

```js
addRow('a', 'b', 'c')
```

There is no good reason to allow that. Requiring an array for column data would make the overall all API smaller and use of the library more consistent.

**Comment by sorensen** [comment]
@gajus I think the point with the method signatures here is to provide the developer the choice on how to call these methods, I couldn't really decide which way I liked better tbh. The logic around this though could certainly be reduced to a 1 liner. Something like `concat.apply([], slice.call(arguments))` which would normalize either form of input.
