### ISSUE TITLE
array input instead of arguments?

### ISSUE THREAD

**Issue by zstew** [sorensen/ascii-table#18]
For my application I'd like to be able to pass arrays of headers and rows in.
I thought I could pull this off by using the "apply" method... but it doesn't work for me.

So I want to say:
var heading = ['a', 'b', 'c']
var row = [1, 2, 3...]
table.setHeading(heading)
table.addRow(row)

but it doesn't like arrays as an input.  So I tried "apply" like this:
table.setHeading.apply(this, heading)
table.addRow.apply(this, row)

but no dice, get an error with both.  Is there a way I can do this?

**Comment by sorensen** [comment]
You should be able to use arrays.

```js
var table = new AsciiTable()
table.setHeading(['a', 'b', 'c'])
table.addRow([1,2,3])
table.addRow(4, 5, 6)
console.log(table)
```

**Comment by zstew** [comment]
Ha! How did I miss that?  I must have been doing something wrong before.   Thanks for your help Sorensen.
