### ISSUE TITLE
support question => indent entire table

### ISSUE THREAD

**Issue by ORESoftware** [sorensen/ascii-table#19]
I looked for indent options and searched for indent in the repo, doesn't seem to be an option.

![screenshot 2016-04-07 16 20 45](https://cloud.githubusercontent.com/assets/11139560/14369789/b8e77e02-fcdc-11e5-88ab-fa4490af8a51.png)

I'd like to indent the table pictured, is there a way to move it over to the right?

let me know thanks!

**Comment by sorensen** [comment]
There is not a built in way to do this, however, the table.toString() is just a string, so you could do something like `table.toString.replace(/\/n/g, '    \n')`

Not entirely sure if that code works, but essentially just reformat the line returns.

**Comment by sorensen** [comment]
Yeah that code is definitely wrong, just trying to convey a theoretical solution, not a literal one.

**Comment by ORESoftware** [comment]
Ok I am working on this to see what I come up with thanks

**Comment by ORESoftware** [comment]
doing this 

   console.log(table.toString().replace('\n','\n\n\n\n'));

just makes the title header really tall LOL

<img width="662" alt="screenshot 2016-04-09 16 21 21" src="https://cloud.githubusercontent.com/assets/11139560/14407029/2fbb7068-fe6f-11e5-8371-283e51b0be73.png">

any other ideas? somehow just need to place the first character of each line with \t + character

**Comment by sorensen** [comment]
Try this.

```js
function indent(str, spacing) {
  return spacing + str.replace(/\n/g, '\n' + spacing)
}
```

Usage: 

```js
var table = new AsciiTable()
// ...
var indented = indent(table.toString(), ' \t')
console.log(indented)

**Comment by sorensen** [comment]
You may also consider a module such as https://github.com/camwest/left-pad

**Comment by sorensen** [comment]
Let me know if you manage to make this work, I will close this regardless as it is outside the scope of this module, but I would like to help you to figure this out before doing so.

**Comment by sorensen** [comment]
@ORESoftware Turns out the module _does_ have a built in way to do this. Checkout the `prefix` option.

https://github.com/sorensen/ascii-table/blob/master/test.js#L99-L121

**Comment by ORESoftware** [comment]
cool! I guess you forget you had implemented that :) :+1:

**Comment by sorensen** [comment]
Little bit of a facepalm moment lol. It has been a long time since I created this module. I have started work on refactoring it to be simpler. Please keep the issues coming, would love to get this library back on track. Also feel free to make feature requests.

I'm closing since we've resolved the issue.
